-- Move tenants.id from BIGSERIAL auto-increment to caller-supplied 12-digit
-- random values. The range is 100_000_000_000 .. 999_999_999_999, generated by
-- the application via crypto/rand and retried on unique-constraint violation.
--
-- All FKs referencing tenants.id are switched to ON UPDATE CASCADE so the
-- re-id of existing rows propagates without breaking referential integrity.

BEGIN;

-- 1. Add ON UPDATE CASCADE to every tenant_id FK so re-iding cascades.
ALTER TABLE files            DROP CONSTRAINT files_tenant_id_fkey;
ALTER TABLE files            ADD  CONSTRAINT files_tenant_id_fkey
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE folders          DROP CONSTRAINT folders_tenant_id_fkey;
ALTER TABLE folders          ADD  CONSTRAINT folders_tenant_id_fkey
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tenant_members   DROP CONSTRAINT tenant_members_tenant_id_fkey;
ALTER TABLE tenant_members   ADD  CONSTRAINT tenant_members_tenant_id_fkey
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE sessions         DROP CONSTRAINT sessions_tenant_id_fkey;
ALTER TABLE sessions         ADD  CONSTRAINT sessions_tenant_id_fkey
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE ON UPDATE CASCADE;

-- 2. Re-id every existing tenant. Each row gets an unused 12-digit value;
--    cascades update files/folders/tenant_members/sessions automatically.
DO $$
DECLARE
    t       RECORD;
    new_id  BIGINT;
BEGIN
    -- Loop over tenants whose id is below the 12-digit floor (i.e. legacy
    -- BIGSERIAL values 1, 2, 3, ...). Anything already in-range is left alone.
    FOR t IN SELECT id FROM tenants WHERE id < 100000000000 ORDER BY id LOOP
        LOOP
            new_id := floor(100000000000 + random() * 899999999999)::BIGINT;
            EXIT WHEN NOT EXISTS (SELECT 1 FROM tenants WHERE id = new_id);
        END LOOP;
        UPDATE tenants SET id = new_id WHERE id = t.id;
    END LOOP;
END $$;

-- 3. Remove the BIGSERIAL default so future INSERTs MUST supply an id.
ALTER TABLE tenants ALTER COLUMN id DROP DEFAULT;

-- 4. Drop the sequence BIGSERIAL created (no longer referenced).
DROP SEQUENCE IF EXISTS tenants_id_seq CASCADE;

COMMIT;
