-- Switch the ticket reference from the sequential, guessable TKT-###### to an
-- opaque, date-stamped code: sk-<MMDDYYYY><9 random digits>, e.g.
-- sk-06112026487193562. Generated by the app on insert. The value still lives
-- in ticket_number (UNIQUE) and is what appears in URLs.

-- App now supplies the reference on insert (creation-date + crypto-random,
-- with collision retry).
ALTER TABLE support_tickets ALTER COLUMN ticket_number DROP DEFAULT;

-- Re-key any existing TKT- tickets to the new format, stamping their own
-- creation date plus 9 random digits.
UPDATE support_tickets
   SET ticket_number = 'sk-' || to_char(created_at, 'MMDDYYYY')
                       || lpad((floor(random() * 1000000000))::bigint::text, 9, '0')
 WHERE ticket_number LIKE 'TKT-%';

-- The old sequence is no longer used.
DROP SEQUENCE IF EXISTS support_ticket_number_seq;
